service: tpt-test-1

provider:
  name: aws
  runtime: nodejs12.x

functions:
  calculator:
    handler: handler.calculator
    events:
      - http:
          path: calc
          method: get

plugins:
  - serverless-offline